"""平台業務表：模板、素材、任務、分鏡、批量、調用記錄、成本賬本、審核、審計、設定

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_app_settings_key")),
    )
    op.create_table(
        "templates",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("video_type", sa.String(length=32), nullable=False),
        sa.Column("ratio", sa.String(length=8), nullable=False),
        sa.Column("resolution", sa.String(length=8), nullable=False),
        sa.Column("min_duration_s", sa.Integer(), nullable=False),
        sa.Column("max_duration_s", sa.Integer(), nullable=False),
        sa.Column("min_shots", sa.Integer(), nullable=False),
        sa.Column("max_shots", sa.Integer(), nullable=False),
        sa.Column("audio_mode", sa.String(length=16), nullable=False),
        sa.Column("subtitle_required", sa.Boolean(), nullable=False),
        sa.Column("style_prefix", sa.Text(), nullable=False),
        sa.Column("prompt_template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("key", name=op.f("uq_templates_key")),
    )
    op.create_table(
        "assets",
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("thumbnail_key", sa.String(length=512), nullable=True),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_assets_owner_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index(op.f("ix_assets_job_id"), "assets", ["job_id"], unique=False)
    op.create_index(op.f("ix_assets_kind"), "assets", ["kind"], unique=False)
    op.create_index(op.f("ix_assets_owner_id"), "assets", ["owner_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_logs_actor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_table(
        "batches",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("source_asset_id", sa.Uuid(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("max_parallel", sa.Integer(), nullable=False),
        sa.Column("draft_mode", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_batches_owner_id_users")),
        sa.ForeignKeyConstraint(
            ["source_asset_id"], ["assets.id"], name=op.f("fk_batches_source_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["templates.id"], name=op.f("fk_batches_template_id_templates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
    )
    op.create_index(op.f("ix_batches_owner_id"), "batches", ["owner_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("template_snapshot", sa.JSON(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("video_type", sa.String(length=32), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("region", sa.String(length=16), nullable=False),
        sa.Column("ratio", sa.String(length=8), nullable=False),
        sa.Column("resolution", sa.String(length=8), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("draft_mode", sa.Boolean(), nullable=False),
        sa.Column("continuous_shots", sa.Boolean(), nullable=False),
        sa.Column("budget_cny", sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=False),
        sa.Column(
            "estimated_cost_cny", sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True
        ),
        sa.Column(
            "actual_cost_cny", sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=False
        ),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("final_asset_id", sa.Uuid(), nullable=True),
        sa.Column("cover_asset_id", sa.Uuid(), nullable=True),
        sa.Column("subtitle_asset_id", sa.Uuid(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_jobs_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["cover_asset_id"], ["assets.id"], name=op.f("fk_jobs_cover_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["final_asset_id"], ["assets.id"], name=op.f("fk_jobs_final_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_jobs_owner_id_users")),
        sa.ForeignKeyConstraint(
            ["subtitle_asset_id"], ["assets.id"], name=op.f("fk_jobs_subtitle_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["templates.id"], name=op.f("fk_jobs_template_id_templates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_batch_id"), "jobs", ["batch_id"], unique=False)
    op.create_index(op.f("ix_jobs_owner_id"), "jobs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_video_type"), "jobs", ["video_type"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("checklist", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_reviews_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], name=op.f("fk_reviews_reviewer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index(op.f("ix_reviews_job_id"), "reviews", ["job_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("visual_prompt", sa.Text(), nullable=False),
        sa.Column("shot_type", sa.String(length=50), nullable=False),
        sa.Column("camera_move", sa.String(length=50), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("needs_first_frame", sa.Boolean(), nullable=False),
        sa.Column("screen_text", sa.Text(), nullable=False),
        sa.Column("first_frame_asset_id", sa.Uuid(), nullable=True),
        sa.Column("first_frame_generated", sa.Boolean(), nullable=False),
        sa.Column("ref_asset_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("remote_task_id", sa.String(length=128), nullable=True),
        sa.Column("video_asset_id", sa.Uuid(), nullable=True),
        sa.Column("last_frame_asset_id", sa.Uuid(), nullable=True),
        sa.Column("audio_asset_id", sa.Uuid(), nullable=True),
        sa.Column("audio_duration_s", sa.Float(), nullable=True),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["audio_asset_id"], ["assets.id"], name=op.f("fk_scenes_audio_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["first_frame_asset_id"],
            ["assets.id"],
            name=op.f("fk_scenes_first_frame_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_scenes_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_frame_asset_id"],
            ["assets.id"],
            name=op.f("fk_scenes_last_frame_asset_id_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["video_asset_id"], ["assets.id"], name=op.f("fk_scenes_video_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenes")),
    )
    op.create_index(op.f("ix_scenes_job_id"), "scenes", ["job_id"], unique=False)
    op.create_table(
        "generation_calls",
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model_key", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("remote_task_id", sa.String(length=128), nullable=True),
        sa.Column("request_summary", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_generation_calls_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"], ["scenes.id"], name=op.f("fk_generation_calls_scene_id_scenes")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_generation_calls_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generation_calls")),
    )
    op.create_index(
        op.f("ix_generation_calls_job_id"), "generation_calls", ["job_id"], unique=False
    )
    op.create_table(
        "cost_ledger",
        sa.Column("generation_call_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("model_key", sa.String(length=32), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=6, asdecimal=False), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=6, asdecimal=False), nullable=False),
        sa.Column("amount_cny", sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generation_call_id"],
            ["generation_calls.id"],
            name=op.f("fk_cost_ledger_generation_call_id_generation_calls"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_cost_ledger_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cost_ledger_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_ledger")),
    )
    op.create_index(op.f("ix_cost_ledger_job_id"), "cost_ledger", ["job_id"], unique=False)
    op.create_index(op.f("ix_cost_ledger_user_id"), "cost_ledger", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cost_ledger_user_id"), table_name="cost_ledger")
    op.drop_index(op.f("ix_cost_ledger_job_id"), table_name="cost_ledger")
    op.drop_table("cost_ledger")
    op.drop_index(op.f("ix_generation_calls_job_id"), table_name="generation_calls")
    op.drop_table("generation_calls")
    op.drop_index(op.f("ix_scenes_job_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_reviews_job_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_jobs_video_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_owner_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_batch_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_batches_owner_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_assets_owner_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_kind"), table_name="assets")
    op.drop_index(op.f("ix_assets_job_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("templates")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
